# Generated by Django 3.1.3 on 2020-11-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_habit_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='entry_time',
        ),
        migrations.AddField(
            model_name='record',
            name='entry_date',
            field=models.DateField(auto_now=True),
        ),
    ]
