# Generated by Django 3.1.3 on 2020-11-09 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201105_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='habit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='core.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.habit'),
        ),
    ]
