# Generated by Django 3.1.3 on 2020-11-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201112_1918'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='unique_record',
        ),
    ]
